# Must extends shani\contracts\BasicConfiguration
config: \apps\tinker\v1\config\Settings

# Test file runner implements features\test\TestRunnerInterface
test: \apps\tinker\v1\tests\TestRunner

# A php class file implements features\console\commands\CustomCommandsInterface
custom_command: \apps\tinker\v1\commands\CustomCommands

# Active configuration profile. The framework does not provide any logic regarding
# this variable. You should handle the logic manually
profile: dev.yml

# Tell whether the application is running or is in maintenance mode
running: true