#!/usr/bin/env php
<?php

use features\console\CommandRegistry;
use shani\launcher\ShaniUtils;

set_include_path(get_include_path() . PATH_SEPARATOR . 'vendor');
spl_autoload_register(function (string $class) {
    require_once str_replace('\\', '/', $class) . '.php';
});
ShaniUtils::define(__DIR__);

if ($argc >= 2) {
    $command = $argv[1];
    unset($argv[0], $argv[1]);
    try {
        echo PHP_EOL;
        $params = array_values($argv);
        (new CommandRegistry())->run($command, ...$params);
    } catch (\Throwable $t) {
        echo '[ERROR] ' . $t->getMessage() . PHP_EOL;
    } finally {
        echo PHP_EOL . 'Done' . PHP_EOL . PHP_EOL;
    }
} else {
    echo '[ERROR] Too few arguments!' . PHP_EOL;
}