#!/usr/bin/env php
<?php

use features\console\CommandRegistry;
use features\console\printer\ConsoleColor;
use features\console\printer\ConsoleIO;
use features\console\printer\PrintedText;

require_once 'classloader.php';

(function (array $arguments) {
    $command = !isset($arguments[1]) ? 'help' : $arguments[1];
    unset($arguments[0], $arguments[1]);
    $registry = new CommandRegistry($command, array_values($arguments));
    try {
        $registry->run();
        exit(0);
    } catch (Throwable $t) {
        if (!$registry->options->quiet) {
            CommandRegistry::printBanner(ConsoleColor::RED);
        }
        ConsoleIO::error(PrintedText::error('[ ERROR ] ')->coloredText . $t->getMessage() . PHP_EOL);
        exit(1);
    }
})($argv);
