#!/usr/bin/env php
<?php

use features\console\CommandRegistry;
use features\console\printer\ConsoleColor;
use features\console\printer\ConsoleIO;
use features\console\printer\PrintedText;
use shani\utils\ShaniUtils;

set_include_path(get_include_path() . PATH_SEPARATOR . 'vendor');
spl_autoload_register(function (string $class) {
    require_once str_replace('\\', '/', $class) . '.php';
});
ShaniUtils::define(__DIR__);

(function (array $arguments) {
    $command = !isset($arguments[1]) ? 'help' : $arguments[1];
    unset($arguments[0], $arguments[1]);
    $registry = new CommandRegistry($command, array_values($arguments));
    try {
        $registry->run();
        exit(0);
    } catch (Throwable $t) {
        if (!$registry->options->quiet) {
            CommandRegistry::printBanner(ConsoleColor::RED);
        }
        ConsoleIO::error(PrintedText::error('[ ERROR ] ')->coloredText . $t->getMessage() . PHP_EOL);
        exit(1);
    }
})($argv);
