include snippets/fastcgi-php.conf;

# Security: Close vulnerabilities
fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
fastcgi_param DOCUMENT_ROOT $realpath_root;

fastcgi_pass unix:$php_fpm_socket;
# Alternatively:
# fastcgi_pass 127.0.0.1:9000;
