# ---------------------------------------------------------
# PORTABLE NGINX CONFIG WITH HTTPS REDIRECT
# ---------------------------------------------------------

## HTTP Server Block (Port 80) - The Redirector
server {
    listen 80;
    listen [::]:80;

    include /var/www/html/{{app_dirpath}}/custom.conf;

    return 301 https://$host$request_uri;
}

    ## HTTPS Server Block (Port 443) - The Application
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # Load custom configuration
    include /var/www/html/{{app_dirpath}}/custom.conf;

    root $project_root;
    index index.php;
    rewrite ^ /index.php?$query_string last;

    # Include the SSL certificate and key
    include snippets/self-signed.conf;
    include snippets/ssl-params.conf;

    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Process PHP files using PHP-FPM
    location ~ \.php$ {
        include /var/www/html/{{app_dirpath}}/dynamic.conf;
    }

    ##################### STATIC FILE HANDLING ####################
    include /var/www/html/{{app_dirpath}}/optimization.conf;

    location {{private_bucket}}/ {
        alias $project_root/{{storage_dir}}/;
        include /var/www/html/{{app_dirpath}}/static.conf;
    }

    location {{public_bucket}}/ {
        alias $project_root/{{asset_dir}}/;
        include /var/www/html/{{app_dirpath}}/static.conf;
    }
    ##################### END STATIC FILE HANDLING ####################
}