# Centralized configuration for the project
server_name localhost dev.shani.v2.local www.dev.shani.v2.local;

# Change this path once when moving the project folder
set $project_root /var/www/html/shani-php;
set $php_fpm_socket /var/run/php/php-fpm.sock;