# BEST PRACTICE: Security & Logging
autoindex off;
access_log off;
log_not_found off;

# BEST PRACTICE: Browser Caching (1 month)
expires 30d;
add_header Cache-Control "public, no-transform";

# Ensure files are served correctly via the alias
try_files $uri $uri/ =404;
