# Must extends shani\contracts\BasicConfiguration
config: \apps\shop\v1\config\Settings

# Test file runner
test: \apps\shop\v1\tests\TestRunner

# Active configuration profile. The framework does not provide any logic regarding
# this variable. You should handle the logic manually
profile: dev.yml