## Shani Framework Configuration.
---
#The IP address server is running on.
IP: "0.0.0.0"
PORTS:
  HTTP: 8008
  HTTPS: 44380
SSL:
  KEY: "/server.key"
  CERT: "/server.crt"
# Display all application errors and server errors. This variable can be
# overridden by application.
DISPLAY_ERRORS: false
TIME_ZONE: Africa/Dar_Es_Salaam
# Maximum payload size in MB allowed to upload.
MAX_PAYLOAD_SIZE: 100
