## Shani Framework Configuration.
---
# Display all application errors and server errors. This variable can be
# overridden by application.
display_errors: true
time_zone: Africa/Dar_Es_Salaam
# Maximum payload size in MB allowed to upload.
max_payload_size: 100
