## Shani Server Configuration.
---
#The IP address server is running on.
IP: "0.0.0.0"
SERVER_PORTS:
  HTTP: 8008
  HTTPS: 44380
# SCHEDULING_ALGORITHM: "PREEMPTIVE, ROUND_ROBIN, FIXED"
SCHEDULING_ALGORITHM: "PREEMPTIVE"
# maximum number of concurrent connections
MAX_CONNECTIONS: 1024
# maximum number of requests a worker process should execute
# before it is automatically restarted by the server
REQ_PER_WORKER: 100
ENABLE_HTTP2: false
SSL:
  KEY: "${SSL_DIR}/server.key"
  CERT: "${SSL_DIR}/server.crt"
# Run server as background process
RUNAS_DAEMON: false
# Display all application errors and server errors.
# This variable can be overridden by application.
DISPLAY_ERRORS: false