# Must extends shani\advisors\Configuration
classpath: \apps\demo\config\Settings
# Active configuration profile. The framework does not provide any logic regarding
# this variable. You should handle the logic manually
profile: dev.yml