# Must extends shani\contracts\BasicConfiguration
config: \{namespace}\{config_dir}\Settings

# Test file runner
test: \{namespace}\{test_dir}\TestRunner

# Active configuration profile. The framework does not provide any logic regarding
# this variable. You should handle the logic manually
profile: dev.yml

# Tell whether the application is running or is in maintenance mode
running: true