# BEST PRACTICE: OS-level optimization
sendfile on;
tcp_nopush on;
tcp_nodelay on;

# BEST PRACTICE: Gzip Compression
gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_types text/* */json */xml */javascript */svg+xml;