# Must extends shani\contracts\BasicPresets
config: \{namespace}\{config_dir}\Settings
# Active configuration profile. The framework does not provide any logic regarding
# this variable. You should handle the logic manually
profile: dev.yml
# Wheter to run application test using provided profile.
testmode: false