## Swoole Server Configuration.
---
# SCHEDULING_ALGORITHM: "ROUND_ROBIN, FIXED, PREEMPTIVE, IPMOD. When ENABLE_HTTP2
# is true, scheduling algorithm MUST be either FIXED or IPMOD"
SCHEDULING_ALGORITHM: "PREEMPTIVE"
ENABLE_HTTP2: false
# maximum number of concurrent connections
MAX_CONNECTIONS: 1024
# maximum number of requests a worker process should execute before it is
# automatically restarted by the server, set 0 for unlimited.
MAX_WORKER_REQUESTS: 1000
# Time in seconds that the server will wait for worker processes to exit
# gracefully before forcing termination.
MAX_WAIT_TIME: 60
# Run the server in background
RUNAS_DAEMON: false
# Redirect insecure HTTP to HTTPS
REDIRECT_INSECURE_REQUEST: true